'use strict';
const $=id=>document.getElementById(id);let token='',tab='users',users=[],servers=[],editing=null;
// Admin token lives in memory only; reloading requires another sign-in.
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,method='GET',body){const r=await fetch(window.YAY_API_BASE+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok){if(r.status===401&&path!='/admin/login')signout();throw Error(d.error||'Request failed');}return d;}
function notice(s){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').hidden=true,7000);}
function signout(){token='';users=[];servers=[];$('login').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true;$('editor').close();$('devices').close();}
$('login-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{token=(await api('/admin/login','POST',{password:$('admin-password').value})).token;$('admin-password').value='';await refresh();$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;}catch(e){notice(e.message);}finally{b.disabled=false;}};
$('logout').onclick=async()=>{try{await api('/admin/logout','POST',{});}catch(e){}signout();};
async function refresh(){const result=await Promise.all([api('/admin/users'),api('/admin/servers')]);users=result[0].users;servers=result[1].servers;$('user-count').textContent=users.length;$('server-count').textContent=servers.filter(s=>s.enabled).length;render();}
function setTab(t){tab=t;$('users-tab').classList.toggle('active',t==='users');$('servers-tab').classList.toggle('active',t==='servers');$('list-title').textContent=t==='users'?'Your people':'Your servers';$('list-help').textContent=t==='users'?'Set their access. Keep it simple.':'Add a connection once. Keep every app up to date.';$('add').textContent=t==='users'?'+ Add person':'+ Add server';$('export-seed').hidden=t!=='servers';$('search').value='';render();}
$('users-tab').onclick=()=>setTab('users');$('servers-tab').onclick=()=>setTab('servers');$('search').oninput=render;
function render(){const list=(tab==='users'?users:servers).filter(x=>(x.username||x.name).toLowerCase().includes($('search').value.toLowerCase()));$('rows').innerHTML=list.length?list.map(x=>{const name=x.username||x.name,active=x.enabled&&(tab==='servers'||x.expires_at>Date.now()/1000);const sub=tab==='users'?`${x.devices_used} / ${x.device_limit} devices · Until ${new Date(x.expires_at*1000).toLocaleDateString()}`:`${x.location||'Location not set'} · ${x.protocol.toUpperCase()}`;return `<div class="row"><div class="identity"><div class="avatar">${escape(name.charAt(0).toUpperCase())}</div><div><strong>${escape(name)}</strong><small>${escape(sub)}</small></div></div><div class="row-actions"><span class="badge ${active?'':'off'}">${active?'ACTIVE':'PAUSED / EXPIRED'}</span>${tab==='users'?`<button data-action="devices" data-id="${x.id}">Devices</button>`:''}<button data-action="edit" data-id="${x.id}">Edit</button><button data-action="toggle" data-id="${x.id}">${x.enabled?'Pause':'Enable'}</button><button data-action="delete" data-id="${x.id}" aria-label="Delete ${escape(name)}">Remove</button></div></div>`;}).join(''):`<div class="empty">${$('search').value?'No matches. Try another name.':tab==='users'?'Your first person starts here. Add an account to give them access.':'No servers yet. Add a server link to get started.'}</div>`;}
$('rows').onclick=async e=>{const b=e.target.closest('button[data-action]');if(!b)return;const x=(tab==='users'?users:servers).find(x=>x.id===b.dataset.id);try{if(b.dataset.action==='edit')openEditor(x);if(b.dataset.action==='devices')await deviceList(x.id);if(b.dataset.action==='toggle'){await api('/admin/'+tab+'/'+x.id,'PATCH',{enabled:x.enabled?0:1});await refresh();}if(b.dataset.action==='delete'&&confirm(`Remove ${x.username||x.name}? ${tab==='users'?'Their account and device registrations will be deleted.':'Clients using this server will disconnect when their access is checked.'}`)){await api('/admin/'+tab+'/'+x.id,'DELETE');await refresh();}}catch(e){notice(e.message);}};
const input=(id,title,type,value='',required=false,extra='')=>`<label>${title}<input id="${id}" type="${type}" value="${escape(value)}" ${required?'required':''} ${extra}></label>`;
function localDate(epoch){const d=new Date(epoch*1000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);}
function openEditor(x){editing=x;$('edit-title').textContent=(x?'Edit ':'Add ')+(tab==='users'?'person':'server');$('form-error').textContent='';$('fields').innerHTML=tab==='users'?input('f-name','Username','text',x?.username||'',true,`minlength="3" maxlength="64" ${x?'disabled':''}`)+input('f-password',x?'New password (leave blank to keep)':'Password','password','',!x,'minlength="10" autocomplete="new-password"')+input('f-limit','Maximum registered devices','number',x?.device_limit||2,true,'min="1" max="100"')+input('f-expiry','Access ends (your local time)','datetime-local',localDate(x?.expires_at||Math.floor(Date.now()/1000)+30*86400),true):input('f-name','Friendly name','text',x?.name||'',true,'placeholder="Singapore · Everyday" maxlength="80"')+input('f-location','Location','text',x?.location||'',false,'placeholder="Singapore"')+input('f-uri',x?'Replacement server link (optional)':'Server link','password','',!x,'placeholder="vless://…" autocomplete="off"')+'<p class="fine">VLESS + TLS / REALITY, VMess, Trojan, or Shadowsocks. TCP, WebSocket and gRPC are supported. Subscription URLs are not server links.</p>';$('editor').showModal();}
$('add').onclick=()=>openEditor(null);$('close').onclick=()=>$('editor').close();$('close-devices').onclick=()=>$('devices').close();
$('edit-form').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{const body=tab==='users'?{username:$('f-name').value,password:$('f-password').value,device_limit:Number($('f-limit').value),expires_at:Math.floor(new Date($('f-expiry').value).getTime()/1000)}:{name:$('f-name').value,location:$('f-location').value,uri:$('f-uri').value};await api('/admin/'+tab+(editing?'/'+editing.id:''),editing?'PATCH':'POST',body);$('editor').close();$('fields').innerHTML='';await refresh();notice('Saved.');}catch(e){$('form-error').textContent=e.message;}finally{$('save').disabled=false;}};
async function deviceList(uid){const {devices}=await api('/admin/users/'+uid+'/devices');$('device-list').innerHTML=devices.length?devices.map(d=>`<div class="row"><div><strong>${escape(d.name)}</strong><small>Last active ${escape(new Date(d.last_seen*1000).toLocaleString())}</small></div><button data-id="${d.id}">Remove</button></div>`).join(''):'<p class="empty">No devices registered yet.</p>';$('device-list').onclick=async e=>{const b=e.target.closest('button');if(!b||!confirm('Remove this device and end its sessions?'))return;try{await api('/admin/devices/'+b.dataset.id,'DELETE');await deviceList(uid);await refresh();}catch(e){notice(e.message);}};if(!$('devices').open)$('devices').showModal();}
$('export-seed').onclick=async()=>{try{const data=await api('/admin/seed');const u=URL.createObjectURL(new Blob([data.seed],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download='seed.enc';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);notice('Copy seed.enc into android/app/src/main/assets before building.');}catch(e){notice(e.message);}};
