using System.IO;
using System.Diagnostics;
using System.Globalization;
using System.Net.Sockets;
using System.Net.NetworkInformation;
using System.Text.Json.Nodes;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace YayVpn;
public partial class MainWindow : Window {
    YayApi api=null!;Tunnel tunnel=null!;JsonArray nodes=new();string lang="en";
    CancellationTokenSource? operation;bool busy;string screen="welcome";
    readonly string languageFile=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"YayVPN","language.txt");
    ComboBox? picker;TextBlock? status;Button? power;WorldMap? map;
    readonly Dictionary<string,(long ms,long at,int revision)> pings=new();
    static readonly Brush Red=new SolidColorBrush(Color.FromRgb(243,75,89)),Green=new SolidColorBrush(Color.FromRgb(76,229,160));
    string T(string en,string zh,string id)=>lang=="zh"?zh:lang=="id"?id:en;
    public MainWindow(){InitializeComponent();try{if(File.Exists(languageFile))lang=File.ReadAllText(languageFile);}catch{}NetworkChange.NetworkAddressChanged+=NetworkChanged;Loaded+=async(_,_)=>{try{api=new();tunnel=new(api);tunnel.Stopped+=()=>Dispatcher.InvokeAsync(()=>{if(screen=="home")ShowHome();});if(api.Token.Length>0){try{await Refresh();}catch(ApiException e) when(e.Status==401||e.Status==403){api.ClearSession();Welcome();}catch{Welcome();}}else Welcome();}catch{MessageBox.Show("Yay VPN could not open secure storage or reach the cloud. Please restart and check your connection.");Close();}};Closed+=(_,_)=>{NetworkChange.NetworkAddressChanged-=NetworkChanged;operation?.Cancel();tunnel?.Dispose();api?.Dispose();};}
    void NetworkChanged(object? sender,EventArgs e){Dispatcher.InvokeAsync(()=>{pings.Clear();});}
    void Base(string title,bool back=false){Root.Children.Clear();var bar=new DockPanel();var b=new Button{Content=back?"←":"⚙",Width=52};b.Click+=(_,_)=>{if(back){if(api.Token.Length>0)ShowHome();else Welcome();}else Settings();};DockPanel.SetDock(b,Dock.Left);bar.Children.Add(b);bar.Children.Add(new TextBlock{Text=title,FontSize=25,FontWeight=FontWeights.Bold,TextAlignment=TextAlignment.Center,Margin=new(0,12,40,20)});Root.Children.Add(bar);}
    void Label(string value,int size=16,Brush? color=null){Root.Children.Add(new TextBlock{Text=value,FontSize=size,Foreground=color??Brushes.White,Margin=new(0,12,0,12)});}
    Button Add(string label,Action action,bool primary=false){var b=new Button{Content=label};if(primary){b.Background=Red;b.Foreground=Brushes.Black;}b.Click+=(_,_)=>action();Root.Children.Add(b);return b;}
    void Welcome(){screen="welcome";Base("YAY VPN");Root.Children.Add(new WorldMap{Height=230});Label(T("Your world. Connected.","连接你的世界。","Duniamu. Terhubung."),30);Add(T("Log in","登录","Masuk"),Login,true);Add(T("Sign up","注册","Daftar"),Contacts);}
    void Login(){screen="login";Base("YAY VPN",true);Label(T("Login ID","账号","ID masuk"));var user=new TextBox{FontSize=18,Padding=new(12)};Root.Children.Add(user);Label(T("Password","密码","Kata sandi"));var password=new PasswordBox{FontSize=18,Padding=new(12)};Root.Children.Add(password);Button? button=null;button=Add(T("Log in","登录","Masuk"),async()=>{button!.IsEnabled=false;try{await api.Login(user.Text.Trim(),password.Password);password.Clear();await Refresh();}catch{MessageBox.Show(T("Sign-in failed. Check your credentials, device limit and access expiry.","登录失败，请检查账号密码、设备上限和有效期。","Masuk gagal. Periksa akun, batas perangkat, dan masa akses."));button.IsEnabled=true;}},true);}
    async Task Refresh(){var b=await api.Call("GET","/v1/bootstrap");nodes=b["servers"]!.AsArray();pings.Clear();ShowHome();}
    void Contacts(){screen="contacts";Base(T("Sign up / Help","注册 / 帮助","Daftar / Bantuan"),true);Label(T("Contact us to receive a login ID and password. Your administrator sets the device limit and access period.","联系我们获取账号密码。管理员将设置设备上限和有效期。","Hubungi kami untuk mendapatkan akun. Admin menetapkan batas perangkat dan masa akses."));Add("Weixin: wxid_3lt1aad36ai822",()=>{Clipboard.SetText("wxid_3lt1aad36ai822");MessageBox.Show(T("Weixin ID copied","微信号已复制","ID Weixin disalin"));});Add("WhatsApp: +371 28 635 209",()=>Open("https://wa.me/37128635209"));Add("Email: dummystorage22@gmail.com",()=>Open("mailto:dummystorage22@gmail.com"));}
    static void Open(string url){try{Process.Start(new ProcessStartInfo(url){UseShellExecute=true});}catch{MessageBox.Show("Open the contact address manually.");}}
    void Settings(){if(busy)return;screen="settings";Base(T("Settings","设置","Pengaturan"),true);Add(T("Help","帮助","Bantuan"),Contacts);var language=new ComboBox{ItemsSource=new[]{"English","中文","Bahasa Indonesia"},SelectedIndex=lang=="zh"?1:lang=="id"?2:0,Margin=new(0,20,0,20)};language.SelectionChanged+=(_,_)=>{lang=new[]{"en","zh","id"}[language.SelectedIndex];try{File.WriteAllText(languageFile,lang);}catch{}Settings();};Root.Children.Add(language);if(api.Token.Length>0)Add(T("Log out","退出登录","Keluar"),async()=>{operation?.Cancel();tunnel.Stop();try{await api.Logout();}catch{}nodes=new();pings.Clear();Welcome();});}
    List<JsonObject> Country(string country)=>nodes.OfType<JsonObject>().Where(n=>n["location"]?.GetValue<string>()==country).ToList();
    void ShowHome(){screen="home";Base("YAY VPN");var countries=nodes.OfType<JsonObject>().Select(n=>n["location"]?.GetValue<string>()??"").Distinct().Order().ToArray();string selected=(picker?.SelectedItem as ComboBoxItem)?.Tag as string??(countries.Contains("Singapore")?"Singapore":countries.FirstOrDefault()??"");picker=new ComboBox{FontSize=19,Padding=new(12),IsEnabled=!tunnel.Connected&&!busy};foreach(var country in countries){var item=new ComboBoxItem{Content=CountryLabel(country),Tag=country};picker.Items.Add(item);if(country==selected)picker.SelectedItem=item;}Root.Children.Add(picker);var expander=new Expander{Header=T("Country pings ▾","国家延迟 ▾","Ping negara ▾"),Foreground=Brushes.White,Margin=new(0,12,0,0)};var list=new StackPanel();foreach(var country in countries){var measured=Country(country).Select(n=>Fresh(n)).Where(n=>n>=0).ToArray();list.Children.Add(new TextBlock{Text=CountryTitle(country)+"   "+(measured.Length>0?measured.Min()+" ms":"—"),Margin=new(6),Foreground=Brushes.White});}expander.Content=list;Root.Children.Add(expander);
        Add(T("Test country pings","测试国家延迟","Uji ping negara"),async()=>{if(busy||tunnel.Connected)return;await Run(async ct=>{await Measure(nodes.OfType<JsonObject>().ToList(),ct);ShowHome();});});
        var hero=new Grid{Height=310};map=new WorldMap{Active=tunnel.Connected};hero.Children.Add(map);power=new Button{Style=(Style)FindResource("PowerButton"),Content="⏻",FontSize=70,Width=180,Height=180,Background=Brushes.Black,Foreground=tunnel.Connected?Green:Red,BorderBrush=tunnel.Connected?Green:Red,BorderThickness=new(2)};power.Click+=async(_,_)=>{if(busy){operation?.Cancel();return;}if(tunnel.Connected){tunnel.Stop();ShowHome();return;}string country=(picker.SelectedItem as ComboBoxItem)?.Tag as string??"";await Run(async ct=>{var group=Country(country);if(group.Any(n=>Fresh(n)<0))await Measure(group,ct);var live=group.Where(n=>Fresh(n)>=0).OrderBy(n=>Fresh(n)).ToList();if(live.Count==0)throw new IOException("No reachable server");long best=Fresh(live[0]);var fast=live.Where(n=>Fresh(n)<=best+Math.Max(10,best/20)).OrderBy(_=>Random.Shared.Next()).ToList();var ordered=fast.Concat(live.Except(fast)).Take(3);Exception? last=null;foreach(var n in ordered){ct.ThrowIfCancellationRequested();try{await tunnel.Connect(n["id"]!.GetValue<string>(),ct);last=null;break;}catch(Exception e){last=e;}}if(last!=null)throw last;ShowHome();});};hero.Children.Add(power);Root.Children.Add(hero);
        status=new TextBlock{Text=tunnel.Connected?T("Connected","已连接","Terhubung"):T("Disconnected","未连接","Terputus"),FontSize=26,TextAlignment=TextAlignment.Center,Foreground=tunnel.Connected?Green:Brushes.White};Root.Children.Add(status);Label(T("TCP ping is a reachability measurement. VPN access is checked separately on connection.","TCP 延迟用于测试可达性，连接时另行验证 VPN 网络访问。","Ping TCP mengukur keterjangkauan. Akses VPN diuji terpisah saat tersambung."),12,Brushes.Gray);Add(T("Refresh locations","刷新地区","Muat ulang lokasi"),async()=>{if(!busy&&!tunnel.Connected)await Run(async _=>await Refresh());});}
    static readonly Dictionary<string,string> CountryCodes=new(){["Singapore"]="SG",["Japan"]="JP",["Hong Kong"]="HK",["United States"]="US",["United Kingdom"]="GB",["Australia"]="AU",["Germany"]="DE",["Spain"]="ES",["Brazil"]="BR",["India"]="IN",["South Africa"]="ZA",["South Korea"]="KR"};
    string CountryTitle(string country){return lang=="en"?country:Translations.TryGetValue(country,out var names)?(lang=="zh"?names.zh:names.id):country;}
    static readonly Dictionary<string,(string zh,string id)> Translations=new(){["Singapore"]=("新加坡","Singapura"),["Japan"]=("日本","Jepang"),["Hong Kong"]=("香港","Hong Kong"),["United States"]=("美国","Amerika Serikat"),["United Kingdom"]=("英国","Britania Raya"),["Australia"]=("澳大利亚","Australia"),["Germany"]=("德国","Jerman"),["Spain"]=("西班牙","Spanyol"),["Brazil"]=("巴西","Brasil"),["India"]=("印度","India"),["South Africa"]=("南非","Afrika Selatan"),["South Korea"]=("韩国","Korea Selatan")};
    StackPanel CountryLabel(string country){var panel=new StackPanel{Orientation=Orientation.Horizontal};panel.Children.Add(new FlagView{Code=CountryCodes.GetValueOrDefault(country,""),Width=30,Height=20,Margin=new(0,0,10,0)});panel.Children.Add(new TextBlock{Text=CountryTitle(country),Foreground=Brushes.Black});return panel;}
    long Fresh(JsonObject node){string id=node["id"]!.GetValue<string>();return pings.TryGetValue(id,out var p)&&Environment.TickCount64-p.at<120000&&p.revision==node["revision"]!.GetValue<int>()?p.ms:-1;}
    async Task Measure(List<JsonObject> group,CancellationToken ct){using var gate=new SemaphoreSlim(6);int done=0;await Task.WhenAll(group.Select(async node=>{await gate.WaitAsync(ct);try{long ms=-1;try{var grant=await api.Call("POST","/v1/connect",new(){["server_id"]=node["id"]!.GetValue<string>()},ct);var outbound=grant["config"]!["outbounds"]![0]!;using var socket=new TcpClient();var watch=Stopwatch.StartNew();using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(1500);await socket.ConnectAsync(outbound["server"]!.GetValue<string>(),outbound["server_port"]!.GetValue<int>(),timeout.Token);ms=Math.Max(1,watch.ElapsedMilliseconds);}catch(ApiException e) when(e.Status==401||e.Status==403){throw;}catch(Exception) when(!ct.IsCancellationRequested){}ct.ThrowIfCancellationRequested();pings[node["id"]!.GetValue<string>()]=(ms,Environment.TickCount64,node["revision"]!.GetValue<int>());if(status!=null)status.Text=$"{++done} / {group.Count}";}finally{gate.Release();}}));}
    async Task Run(Func<CancellationToken,Task> action){busy=true;operation=new();if(picker!=null)picker.IsEnabled=false;try{await action(operation.Token);}catch(OperationCanceledException){tunnel.Stop();}catch{tunnel.Stop();MessageBox.Show(T("Connection failed. Check access or choose another country.","连接失败，请检查账号权限或选择其他国家。","Koneksi gagal. Periksa akses atau pilih negara lain."));}finally{busy=false;operation.Dispose();operation=null;if(screen=="home")ShowHome();}}
}
